INSERT INTO am.Categories (name, nameSlugify, meta, data, createdAt, updatedAt, ParentCategoryId) values ('Iphone 6/6S', 'iphone-6-6s', 8, '{"info":["Case por Arte Manifiesto Lab","Fundas de una pieza con cierre a presión","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"15 grs","description":"Dale un estilo nuevo a tu celular. Estos cases estan hechos de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo.","price":48.73}', NOW(), NOW(), 45),
('Iphone 5/5S/SE', 'iphone-5-5s-se', 8, '{"info":["Case por Arte Manifiesto Lab","Fundas de una pieza con cierre a presión","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"15 grs","description":"Dale un estilo nuevo a tu celular. Estos cases estan hechos de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo.","price":48.73}', NOW(), NOW(), 45),
('Iphone 4/4S', 'iphone-4-4s', 8, '{"info":["Case por Arte Manifiesto Lab","Fundas de una pieza con cierre a presión","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"15 grs","description":"Dale un estilo nuevo a tu celular. Estos cases estan hechos de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo.","price":48.73}', NOW(), NOW(), 45),
('Galaxy S4', 'galaxy-s4', 8, '{"info":["Case por Arte Manifiesto Lab","Fundas de una pieza con cierre a presión","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"15 grs","description":"Dale un estilo nuevo a tu celular. Estos cases estan hechos de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo.","price":48.73}', NOW(), NOW(), 46),
('Galaxy S5', 'galaxy-s5', 8, '{"info":["Case por Arte Manifiesto Lab","Fundas de una pieza con cierre a presión","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"15 grs","description":"Dale un estilo nuevo a tu celular. Estos cases estan hechos de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo.","price":48.73}', NOW(), NOW(), 46),
('Galaxy S6', 'galaxy-s6', 8, '{"info":["Case por Arte Manifiesto Lab","Fundas de una pieza con cierre a presión","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"15 grs","description":"Dale un estilo nuevo a tu celular. Estos cases estan hechos de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo.","price":48.73}', NOW(), NOW(), 46),
('Algodón A3', 'algodon-a3', 8, '{"info":["Print de algodon por Arte Manifiesto Lab","Tintas Originales","Material: 100% Algodon","Acabado: Mate"],"weight":"100 grs","description":"Personaliza tu espacio con un print giclee de alta calidad sobre un papel 100% algodon, matte y de acabado ultra suave usando tintas Epson K3 las cuales proveen colores vivos y duraderos.","price":69.92}', NOW(), NOW(), 47),
('Algodón A4', 'algodon-a4', 8, '{"info":["Print de algodon por Arte Manifiesto Lab","Tintas Originales","Material: 100% Algodon","Acabado: Mate"],"weight":"100 grs","description":"Personaliza tu espacio con un print giclee de alta calidad sobre un papel 100% algodon, matte y de acabado ultra suave usando tintas Epson K3 las cuales proveen colores vivos y duraderos.","price":34.60}', NOW(), NOW(), 47),
('11 OZ', '11-oz', 8, '{"info":["Taza por Arte Manifiesto Lab","Diseño estampado en toda la superficie","Aptas para lavavajillas","Material: Cerámica"],"weight":"100 grs","description":"Empieza tu día con arte mientras desayunas o tomas un café. Su contruccion en ceramica las hace perfectas para el uso con lavavajillas y micro-ondas.","price":19.58}', NOW(), NOW(), 48);

INSERT INTO am.Categories (name, nameSlugify, meta, createdAt, updatedAt, ParentCategoryId) values ('Iphone Cases', 'iphone-case', 7, NOW(), NOW(), 44),
('Galaxy Cases', 'galaxy-cases', 7, NOW(), NOW(), 44),
('Prints', 'prints', 7, NOW(), NOW(), 44),
('Tazas', 'tazas', 7, NOW(), NOW(), 44);

INSERT INTO am.Categories (name, nameSlugify, meta, createdAt, updatedAt) values ('Producto AM', 'producto-am', 6, NOW(), NOW());



INSERT INTO am.Categories (name, nameSlugify, meta, data, createdAt, updatedAt, ParentCategoryId) values ('Mini Print', 'mini-print', 8, '{"info":["Mini Print por Arte Manifiesto Lab","Tintas Originales","Material: Vinilo sobre celtex ","Acabado: Mate"],"weight":"100 grs","Personaliza tu espacio con un print de vinilo sobre celtex de alta calidad y de acabado mate. Incluye un marco personalizado de Grolsch #PaintProyect.","price":20,19}', NOW(), NOW(), 47);