INSERT INTO am.Categories (name, nameSlugify, meta, data, createdAt, updatedAt, ParentCategoryId) values ('Iphone 6/6S', 'iphone-6-6s', 8, '{"info":{"Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"},"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":45}', NOW(), NOW(), 45),
('Iphone 5/5S/SE', 'iphone-5-5s-se', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":45}', NOW(), NOW(), 45),
('Iphone 4/4S', 'iphone-4-4s', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":45}', NOW(), NOW(), 45),
('Galaxy S4', 'galaxy-s4', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":45}', NOW(), NOW(), 46),
('Galaxy S5', 'galaxy-s5', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":45}', NOW(), NOW(), 46),
('Galaxy S6', 'galaxy-s6', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":45}', NOW(), NOW(), 46),
('Algodón A3', 'algodon-a3', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":100}', NOW(), NOW(), 47),
('Algodón A4', 'algodon-a4', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":50}', NOW(), NOW(), 47),
('11 OZ', '11-oz', 8, '{"info":["Case por Arte Manifiesto","Material: Polímero de alta densidad","Acabado: Mate"],"weight":"100 grs","description":"El case esta hecho de materiales duraderos a prueba de golpes y de caidas. Colores nítidos permiten hacer de este un producto ideal para tí o un regalo","price":20}', NOW(), NOW(), 48);

INSERT INTO am.Categories (name, nameSlugify, meta, createdAt, updatedAt, ParentCategoryId) values ('Iphone Case', 'iphone-case', 7, NOW(), NOW(), 44),
('Galaxy Case', 'galaxy-case', 7, NOW(), NOW(), 44),
('Print', 'print', 7, NOW(), NOW(), 44),
('Taza', 'taza', 7, NOW(), NOW(), 44);

INSERT INTO am.Categories (name, nameSlugify, meta, createdAt, updatedAt) values ('Producto AM', 'producto-am', 6, NOW(), NOW());